// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/p2p/conn_msgs.proto

package p2p

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PacketPing struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PacketPing) Reset()         { *m = PacketPing{} }
func (m *PacketPing) String() string { return proto.CompactTextString(m) }
func (*PacketPing) ProtoMessage()    {}
func (*PacketPing) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c680f0b24d73fe7, []int{0}
}
func (m *PacketPing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PacketPing.Unmarshal(m, b)
}
func (m *PacketPing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PacketPing.Marshal(b, m, deterministic)
}
func (m *PacketPing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PacketPing.Merge(m, src)
}
func (m *PacketPing) XXX_Size() int {
	return xxx_messageInfo_PacketPing.Size(m)
}
func (m *PacketPing) XXX_DiscardUnknown() {
	xxx_messageInfo_PacketPing.DiscardUnknown(m)
}

var xxx_messageInfo_PacketPing proto.InternalMessageInfo

type PacketPong struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PacketPong) Reset()         { *m = PacketPong{} }
func (m *PacketPong) String() string { return proto.CompactTextString(m) }
func (*PacketPong) ProtoMessage()    {}
func (*PacketPong) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c680f0b24d73fe7, []int{1}
}
func (m *PacketPong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PacketPong.Unmarshal(m, b)
}
func (m *PacketPong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PacketPong.Marshal(b, m, deterministic)
}
func (m *PacketPong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PacketPong.Merge(m, src)
}
func (m *PacketPong) XXX_Size() int {
	return xxx_messageInfo_PacketPong.Size(m)
}
func (m *PacketPong) XXX_DiscardUnknown() {
	xxx_messageInfo_PacketPong.DiscardUnknown(m)
}

var xxx_messageInfo_PacketPong proto.InternalMessageInfo

type PacketMsg struct {
	ChannelID            int32    `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	EOF                  int32    `protobuf:"varint,2,opt,name=eof,proto3" json:"eof,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PacketMsg) Reset()         { *m = PacketMsg{} }
func (m *PacketMsg) String() string { return proto.CompactTextString(m) }
func (*PacketMsg) ProtoMessage()    {}
func (*PacketMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c680f0b24d73fe7, []int{2}
}
func (m *PacketMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PacketMsg.Unmarshal(m, b)
}
func (m *PacketMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PacketMsg.Marshal(b, m, deterministic)
}
func (m *PacketMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PacketMsg.Merge(m, src)
}
func (m *PacketMsg) XXX_Size() int {
	return xxx_messageInfo_PacketMsg.Size(m)
}
func (m *PacketMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PacketMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PacketMsg proto.InternalMessageInfo

func (m *PacketMsg) GetChannelID() int32 {
	if m != nil {
		return m.ChannelID
	}
	return 0
}

func (m *PacketMsg) GetEOF() int32 {
	if m != nil {
		return m.EOF
	}
	return 0
}

func (m *PacketMsg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Packet struct {
	// Types that are valid to be assigned to Sum:
	//	*Packet_PacketPing
	//	*Packet_PacketPong
	//	*Packet_PacketMsg
	Sum                  isPacket_Sum `protobuf_oneof:"sum"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c680f0b24d73fe7, []int{3}
}
func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

type isPacket_Sum interface {
	isPacket_Sum()
}

type Packet_PacketPing struct {
	PacketPing *PacketPing `protobuf:"bytes,1,opt,name=packet_ping,json=packetPing,proto3,oneof" json:"packet_ping,omitempty"`
}
type Packet_PacketPong struct {
	PacketPong *PacketPong `protobuf:"bytes,2,opt,name=packet_pong,json=packetPong,proto3,oneof" json:"packet_pong,omitempty"`
}
type Packet_PacketMsg struct {
	PacketMsg *PacketMsg `protobuf:"bytes,3,opt,name=packet_msg,json=packetMsg,proto3,oneof" json:"packet_msg,omitempty"`
}

func (*Packet_PacketPing) isPacket_Sum() {}
func (*Packet_PacketPong) isPacket_Sum() {}
func (*Packet_PacketMsg) isPacket_Sum()  {}

func (m *Packet) GetSum() isPacket_Sum {
	if m != nil {
		return m.Sum
	}
	return nil
}

func (m *Packet) GetPacketPing() *PacketPing {
	if x, ok := m.GetSum().(*Packet_PacketPing); ok {
		return x.PacketPing
	}
	return nil
}

func (m *Packet) GetPacketPong() *PacketPong {
	if x, ok := m.GetSum().(*Packet_PacketPong); ok {
		return x.PacketPong
	}
	return nil
}

func (m *Packet) GetPacketMsg() *PacketMsg {
	if x, ok := m.GetSum().(*Packet_PacketMsg); ok {
		return x.PacketMsg
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Packet) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Packet_PacketPing)(nil),
		(*Packet_PacketPong)(nil),
		(*Packet_PacketMsg)(nil),
	}
}

func init() {
	proto.RegisterType((*PacketPing)(nil), "tendermint.proto.p2p.PacketPing")
	proto.RegisterType((*PacketPong)(nil), "tendermint.proto.p2p.PacketPong")
	proto.RegisterType((*PacketMsg)(nil), "tendermint.proto.p2p.PacketMsg")
	proto.RegisterType((*Packet)(nil), "tendermint.proto.p2p.Packet")
}

func init() { proto.RegisterFile("proto/p2p/conn_msgs.proto", fileDescriptor_8c680f0b24d73fe7) }

var fileDescriptor_8c680f0b24d73fe7 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xc1, 0x4f, 0xc2, 0x30,
	0x14, 0xc6, 0x9d, 0x13, 0xcc, 0x1e, 0x78, 0x69, 0x3c, 0x80, 0x17, 0x08, 0x07, 0xc3, 0x81, 0x6c,
	0xc9, 0xfc, 0x07, 0x0c, 0xa8, 0x91, 0x03, 0x91, 0xec, 0xe8, 0x65, 0x19, 0xed, 0xec, 0x1a, 0xd9,
	0x7b, 0xcd, 0x56, 0x0e, 0xfe, 0xad, 0x26, 0x1c, 0xf8, 0x4b, 0x0c, 0x2d, 0x32, 0x4c, 0x8c, 0xde,
	0xbe, 0xef, 0xcb, 0xeb, 0xef, 0x7d, 0x6d, 0xa1, 0xaf, 0x2b, 0x32, 0x14, 0xe9, 0x58, 0x47, 0x9c,
	0x10, 0xd3, 0xb2, 0x96, 0x75, 0x68, 0x33, 0x76, 0x6d, 0x72, 0x14, 0x79, 0x55, 0x2a, 0x34, 0x2e,
	0x09, 0x75, 0xac, 0x6f, 0x6e, 0x4d, 0xa1, 0x2a, 0x91, 0xea, 0xac, 0x32, 0x1f, 0x91, 0x3b, 0x2c,
	0x49, 0x52, 0xa3, 0xdc, 0xec, 0xa8, 0x0b, 0xb0, 0xcc, 0xf8, 0x7b, 0x6e, 0x96, 0x0a, 0xe5, 0x89,
	0x23, 0x94, 0xa3, 0x02, 0x02, 0xe7, 0x16, 0xb5, 0x64, 0x13, 0x00, 0x5e, 0x64, 0x88, 0xf9, 0x3a,
	0x55, 0xa2, 0xe7, 0x0d, 0xbd, 0x71, 0x6b, 0x7a, 0xb5, 0xdb, 0x0e, 0x82, 0x99, 0x4b, 0xe7, 0x0f,
	0x49, 0x70, 0x18, 0x98, 0x0b, 0xd6, 0x07, 0x3f, 0xa7, 0xb7, 0xde, 0xb9, 0x1d, 0xbb, 0xdc, 0x6d,
	0x07, 0xfe, 0xe3, 0xcb, 0x53, 0xb2, 0xcf, 0x18, 0x83, 0x0b, 0x91, 0x99, 0xac, 0xe7, 0x0f, 0xbd,
	0x71, 0x37, 0xb1, 0x7a, 0xf4, 0xe9, 0x41, 0xdb, 0xad, 0x62, 0x33, 0xe8, 0x68, 0xab, 0x52, 0xad,
	0x50, 0xda, 0x45, 0x9d, 0x78, 0x18, 0xfe, 0x76, 0xc9, 0xb0, 0x69, 0xfe, 0x7c, 0x96, 0x80, 0x3e,
	0xba, 0x53, 0x08, 0xa1, 0xb4, 0x35, 0xfe, 0x83, 0xd0, 0x0f, 0x08, 0xa1, 0x64, 0xf7, 0x70, 0x70,
	0xfb, 0xd7, 0xb6, 0x75, 0x3b, 0xf1, 0xe0, 0x2f, 0xc6, 0xa2, 0xde, 0x23, 0x02, 0xfd, 0x6d, 0xa6,
	0x2d, 0xf0, 0xeb, 0x4d, 0x39, 0x0d, 0x5f, 0x27, 0x52, 0x99, 0x62, 0xb3, 0x0a, 0x39, 0x95, 0x91,
	0x58, 0xf1, 0x22, 0x53, 0xc8, 0xd7, 0xb4, 0x11, 0x51, 0x43, 0x8b, 0x8e, 0x3f, 0xbc, 0x6a, 0x5b,
	0x79, 0xf7, 0x15, 0x00, 0x00, 0xff, 0xff, 0xc1, 0x71, 0x5f, 0x47, 0xf5, 0x01, 0x00, 0x00,
}
