// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/p2p/types.proto

package p2p

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type NetAddress struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IP                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 uint32   `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Str                  string   `protobuf:"bytes,4,opt,name=str,proto3" json:"str,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetAddress) Reset()         { *m = NetAddress{} }
func (m *NetAddress) String() string { return proto.CompactTextString(m) }
func (*NetAddress) ProtoMessage()    {}
func (*NetAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c4320c1810ca85c, []int{0}
}
func (m *NetAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetAddress.Unmarshal(m, b)
}
func (m *NetAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetAddress.Marshal(b, m, deterministic)
}
func (m *NetAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetAddress.Merge(m, src)
}
func (m *NetAddress) XXX_Size() int {
	return xxx_messageInfo_NetAddress.Size(m)
}
func (m *NetAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_NetAddress.DiscardUnknown(m)
}

var xxx_messageInfo_NetAddress proto.InternalMessageInfo

func (m *NetAddress) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *NetAddress) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *NetAddress) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *NetAddress) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

type ProtocolVersion struct {
	P2P                  uint64   `protobuf:"varint,1,opt,name=p2p,proto3" json:"p2p,omitempty"`
	Block                uint64   `protobuf:"varint,2,opt,name=block,proto3" json:"block,omitempty"`
	App                  uint64   `protobuf:"varint,3,opt,name=app,proto3" json:"app,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtocolVersion) Reset()         { *m = ProtocolVersion{} }
func (m *ProtocolVersion) String() string { return proto.CompactTextString(m) }
func (*ProtocolVersion) ProtoMessage()    {}
func (*ProtocolVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c4320c1810ca85c, []int{1}
}
func (m *ProtocolVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtocolVersion.Unmarshal(m, b)
}
func (m *ProtocolVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtocolVersion.Marshal(b, m, deterministic)
}
func (m *ProtocolVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtocolVersion.Merge(m, src)
}
func (m *ProtocolVersion) XXX_Size() int {
	return xxx_messageInfo_ProtocolVersion.Size(m)
}
func (m *ProtocolVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtocolVersion.DiscardUnknown(m)
}

var xxx_messageInfo_ProtocolVersion proto.InternalMessageInfo

func (m *ProtocolVersion) GetP2P() uint64 {
	if m != nil {
		return m.P2P
	}
	return 0
}

func (m *ProtocolVersion) GetBlock() uint64 {
	if m != nil {
		return m.Block
	}
	return 0
}

func (m *ProtocolVersion) GetApp() uint64 {
	if m != nil {
		return m.App
	}
	return 0
}

type DefaultNodeInfo struct {
	ProtocolVersion      ProtocolVersion      `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version"`
	DefaultNodeID        string               `protobuf:"bytes,2,opt,name=default_node_id,json=defaultNodeId,proto3" json:"default_node_id,omitempty"`
	ListenAddr           string               `protobuf:"bytes,3,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`
	Network              string               `protobuf:"bytes,4,opt,name=network,proto3" json:"network,omitempty"`
	Version              string               `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Channels             []byte               `protobuf:"bytes,6,opt,name=channels,proto3" json:"channels,omitempty"`
	Moniker              string               `protobuf:"bytes,7,opt,name=moniker,proto3" json:"moniker,omitempty"`
	Other                DefaultNodeInfoOther `protobuf:"bytes,8,opt,name=other,proto3" json:"other"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DefaultNodeInfo) Reset()         { *m = DefaultNodeInfo{} }
func (m *DefaultNodeInfo) String() string { return proto.CompactTextString(m) }
func (*DefaultNodeInfo) ProtoMessage()    {}
func (*DefaultNodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c4320c1810ca85c, []int{2}
}
func (m *DefaultNodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefaultNodeInfo.Unmarshal(m, b)
}
func (m *DefaultNodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefaultNodeInfo.Marshal(b, m, deterministic)
}
func (m *DefaultNodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefaultNodeInfo.Merge(m, src)
}
func (m *DefaultNodeInfo) XXX_Size() int {
	return xxx_messageInfo_DefaultNodeInfo.Size(m)
}
func (m *DefaultNodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DefaultNodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DefaultNodeInfo proto.InternalMessageInfo

func (m *DefaultNodeInfo) GetProtocolVersion() ProtocolVersion {
	if m != nil {
		return m.ProtocolVersion
	}
	return ProtocolVersion{}
}

func (m *DefaultNodeInfo) GetDefaultNodeID() string {
	if m != nil {
		return m.DefaultNodeID
	}
	return ""
}

func (m *DefaultNodeInfo) GetListenAddr() string {
	if m != nil {
		return m.ListenAddr
	}
	return ""
}

func (m *DefaultNodeInfo) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *DefaultNodeInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *DefaultNodeInfo) GetChannels() []byte {
	if m != nil {
		return m.Channels
	}
	return nil
}

func (m *DefaultNodeInfo) GetMoniker() string {
	if m != nil {
		return m.Moniker
	}
	return ""
}

func (m *DefaultNodeInfo) GetOther() DefaultNodeInfoOther {
	if m != nil {
		return m.Other
	}
	return DefaultNodeInfoOther{}
}

type DefaultNodeInfoOther struct {
	TxIndex              string   `protobuf:"bytes,1,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`
	RPCAdddress          string   `protobuf:"bytes,2,opt,name=rpc_address,json=rpcAddress,proto3" json:"rpc_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DefaultNodeInfoOther) Reset()         { *m = DefaultNodeInfoOther{} }
func (m *DefaultNodeInfoOther) String() string { return proto.CompactTextString(m) }
func (*DefaultNodeInfoOther) ProtoMessage()    {}
func (*DefaultNodeInfoOther) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c4320c1810ca85c, []int{3}
}
func (m *DefaultNodeInfoOther) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefaultNodeInfoOther.Unmarshal(m, b)
}
func (m *DefaultNodeInfoOther) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefaultNodeInfoOther.Marshal(b, m, deterministic)
}
func (m *DefaultNodeInfoOther) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefaultNodeInfoOther.Merge(m, src)
}
func (m *DefaultNodeInfoOther) XXX_Size() int {
	return xxx_messageInfo_DefaultNodeInfoOther.Size(m)
}
func (m *DefaultNodeInfoOther) XXX_DiscardUnknown() {
	xxx_messageInfo_DefaultNodeInfoOther.DiscardUnknown(m)
}

var xxx_messageInfo_DefaultNodeInfoOther proto.InternalMessageInfo

func (m *DefaultNodeInfoOther) GetTxIndex() string {
	if m != nil {
		return m.TxIndex
	}
	return ""
}

func (m *DefaultNodeInfoOther) GetRPCAdddress() string {
	if m != nil {
		return m.RPCAdddress
	}
	return ""
}

func init() {
	proto.RegisterType((*NetAddress)(nil), "tendermint.proto.p2p.NetAddress")
	proto.RegisterType((*ProtocolVersion)(nil), "tendermint.proto.p2p.ProtocolVersion")
	proto.RegisterType((*DefaultNodeInfo)(nil), "tendermint.proto.p2p.DefaultNodeInfo")
	proto.RegisterType((*DefaultNodeInfoOther)(nil), "tendermint.proto.p2p.DefaultNodeInfoOther")
}

func init() { proto.RegisterFile("proto/p2p/types.proto", fileDescriptor_5c4320c1810ca85c) }

var fileDescriptor_5c4320c1810ca85c = []byte{
	// 479 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0x41, 0x6f, 0xda, 0x30,
	0x14, 0xc7, 0x47, 0x48, 0x81, 0x3e, 0x86, 0xe8, 0x2c, 0x36, 0xa5, 0xbd, 0x04, 0x21, 0x6d, 0x42,
	0xd3, 0x94, 0x4c, 0xec, 0xb4, 0x63, 0x19, 0x9a, 0xc4, 0xa5, 0x43, 0xd6, 0xd4, 0xc3, 0x2e, 0x51,
	0x12, 0xbb, 0xc4, 0x22, 0xd8, 0x96, 0x63, 0x36, 0xfa, 0x0d, 0xf7, 0x29, 0x72, 0xe0, 0x4b, 0xec,
	0x3a, 0xd9, 0x4e, 0x5b, 0x84, 0xb8, 0xbd, 0xff, 0xdf, 0xef, 0xe5, 0xff, 0xfc, 0x93, 0x03, 0x6f,
	0xa5, 0x12, 0x5a, 0xc4, 0x72, 0x26, 0x63, 0xfd, 0x28, 0x69, 0x15, 0x59, 0x8d, 0x46, 0x9a, 0x72,
	0x42, 0xd5, 0x96, 0x71, 0xed, 0x9c, 0x48, 0xce, 0xe4, 0xcd, 0x07, 0x5d, 0x30, 0x45, 0x12, 0x99,
	0x2a, 0xfd, 0x18, 0xbb, 0xc1, 0xb5, 0x58, 0x8b, 0x97, 0xca, 0xf5, 0x4e, 0x32, 0x80, 0x3b, 0xaa,
	0x6f, 0x09, 0x51, 0xb4, 0xaa, 0xd0, 0x3b, 0xf0, 0x18, 0x09, 0x5a, 0xe3, 0xd6, 0xf4, 0x72, 0xde,
	0x39, 0xd4, 0xa1, 0xb7, 0x5c, 0x60, 0x8f, 0x11, 0xeb, 0xcb, 0xc0, 0x3b, 0xf2, 0x57, 0xd8, 0x63,
	0x12, 0x21, 0xf0, 0xa5, 0x50, 0x3a, 0x68, 0x8f, 0x5b, 0xd3, 0x01, 0xb6, 0x35, 0xba, 0x82, 0x76,
	0xa5, 0x55, 0xe0, 0x9b, 0x66, 0x6c, 0xca, 0xc9, 0x4f, 0x18, 0xae, 0x4c, 0x58, 0x2e, 0xca, 0x7b,
	0xaa, 0x2a, 0x26, 0x38, 0xba, 0x86, 0xb6, 0x9c, 0x49, 0x9b, 0xe4, 0xcf, 0xbb, 0x87, 0x3a, 0x6c,
	0xaf, 0x66, 0x2b, 0x6c, 0x3c, 0x34, 0x82, 0x8b, 0xac, 0x14, 0xf9, 0xc6, 0xc6, 0xf9, 0xd8, 0x09,
	0xf3, 0xd5, 0x54, 0x4a, 0x1b, 0xe4, 0x63, 0x53, 0x4e, 0xfe, 0x79, 0x30, 0x5c, 0xd0, 0x87, 0x74,
	0x57, 0xea, 0x3b, 0x41, 0xe8, 0x92, 0x3f, 0x08, 0x74, 0x0f, 0x57, 0xb2, 0x49, 0x4a, 0x7e, 0xbb,
	0x28, 0x9b, 0xd1, 0x9f, 0xbd, 0x8f, 0xce, 0x61, 0x8a, 0x4e, 0xf6, 0x9a, 0xfb, 0x7f, 0xeb, 0xf0,
	0x15, 0x1e, 0xca, 0x93, 0x75, 0xbf, 0xc2, 0x90, 0xb8, 0xa8, 0x84, 0x0b, 0x42, 0x13, 0x46, 0x1a,
	0x18, 0x6f, 0x0e, 0x75, 0x38, 0x38, 0xde, 0x62, 0x81, 0x07, 0xe4, 0x48, 0x12, 0x14, 0x42, 0xbf,
	0x64, 0x95, 0xa6, 0x3c, 0x49, 0x09, 0x51, 0xf6, 0x02, 0x97, 0x18, 0x9c, 0x65, 0xb0, 0xa3, 0x00,
	0xba, 0x9c, 0xea, 0x3f, 0x42, 0x6d, 0x1a, 0x66, 0x4f, 0xd2, 0x9c, 0x3c, 0x5d, 0xe2, 0xc2, 0x9d,
	0x34, 0x12, 0xdd, 0x40, 0x2f, 0x2f, 0x52, 0xce, 0x69, 0x59, 0x05, 0x9d, 0x71, 0x6b, 0xfa, 0x1a,
	0x3f, 0x6b, 0x33, 0xb5, 0x15, 0x9c, 0x6d, 0xa8, 0x0a, 0xba, 0x6e, 0xaa, 0x91, 0xe8, 0x3b, 0x5c,
	0x08, 0x5d, 0x50, 0x15, 0xf4, 0x2c, 0x92, 0x8f, 0xe7, 0x91, 0x9c, 0x30, 0xfd, 0x61, 0x26, 0x1a,
	0x2e, 0x6e, 0x7c, 0x92, 0xc3, 0xe8, 0x5c, 0x13, 0xba, 0x86, 0x9e, 0xde, 0x27, 0x8c, 0x13, 0xba,
	0x77, 0x6f, 0x08, 0x77, 0xf5, 0x7e, 0x69, 0x24, 0xfa, 0x0c, 0x7d, 0x25, 0x73, 0x8b, 0x80, 0x56,
	0x55, 0x03, 0x6f, 0x78, 0xa8, 0xc3, 0x3e, 0x5e, 0x7d, 0xbb, 0x25, 0xce, 0xc6, 0xa0, 0x64, 0xde,
	0x3c, 0xc5, 0x79, 0xf4, 0xeb, 0xd3, 0x9a, 0xe9, 0x62, 0x97, 0x45, 0xb9, 0xd8, 0xc6, 0x24, 0xcb,
	0x8b, 0x94, 0xf1, 0xbc, 0x14, 0x3b, 0x12, 0xbf, 0xac, 0x1d, 0x3f, 0xff, 0x12, 0x59, 0xc7, 0x96,
	0x5f, 0xfe, 0x07, 0x00, 0x00, 0xff, 0xff, 0xbb, 0xc2, 0x18, 0x84, 0x26, 0x03, 0x00, 0x00,
}
