// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/crypto/merkle/types.proto

package merkle

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SimpleProof struct {
	Total                int64    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Index                int64    `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	LeafHash             []byte   `protobuf:"bytes,3,opt,name=leaf_hash,json=leafHash,proto3" json:"leaf_hash,omitempty"`
	Aunts                [][]byte `protobuf:"bytes,4,rep,name=aunts,proto3" json:"aunts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleProof) Reset()         { *m = SimpleProof{} }
func (m *SimpleProof) String() string { return proto.CompactTextString(m) }
func (*SimpleProof) ProtoMessage()    {}
func (*SimpleProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_57e39eefdaf7ae96, []int{0}
}
func (m *SimpleProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleProof.Unmarshal(m, b)
}
func (m *SimpleProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleProof.Marshal(b, m, deterministic)
}
func (m *SimpleProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleProof.Merge(m, src)
}
func (m *SimpleProof) XXX_Size() int {
	return xxx_messageInfo_SimpleProof.Size(m)
}
func (m *SimpleProof) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleProof.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleProof proto.InternalMessageInfo

func (m *SimpleProof) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *SimpleProof) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *SimpleProof) GetLeafHash() []byte {
	if m != nil {
		return m.LeafHash
	}
	return nil
}

func (m *SimpleProof) GetAunts() [][]byte {
	if m != nil {
		return m.Aunts
	}
	return nil
}

func init() {
	proto.RegisterType((*SimpleProof)(nil), "tendermint.proto.crypto.merkle.SimpleProof")
}

func init() { proto.RegisterFile("proto/crypto/merkle/types.proto", fileDescriptor_57e39eefdaf7ae96) }

var fileDescriptor_57e39eefdaf7ae96 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xcf, 0x31, 0x4b, 0xc7, 0x30,
	0x10, 0x05, 0x70, 0x6a, 0x55, 0x34, 0x76, 0x2a, 0x0e, 0x01, 0x41, 0x8b, 0x53, 0xa7, 0x64, 0x10,
	0xc4, 0xd9, 0xc9, 0x51, 0xea, 0xe6, 0x22, 0x69, 0x72, 0x35, 0xc1, 0x24, 0x17, 0x92, 0x2b, 0xd8,
	0x6f, 0x2f, 0x6d, 0x06, 0x97, 0xff, 0xf8, 0x7e, 0xf7, 0x0e, 0xee, 0xd8, 0x43, 0xca, 0x48, 0x28,
	0x75, 0xde, 0x12, 0xa1, 0x0c, 0x90, 0x7f, 0x3c, 0x48, 0xda, 0x12, 0x14, 0x71, 0x4c, 0xfa, 0x7b,
	0x82, 0x68, 0x20, 0x07, 0x17, 0xa9, 0x8a, 0xa8, 0x5d, 0x51, 0xbb, 0x8f, 0x9e, 0xdd, 0x7c, 0xb8,
	0x90, 0x3c, 0xbc, 0x67, 0xc4, 0xa5, 0xbf, 0x65, 0x17, 0x84, 0xa4, 0x3c, 0x6f, 0x86, 0x66, 0x6c,
	0xa7, 0x1a, 0x76, 0x75, 0xd1, 0xc0, 0x2f, 0x3f, 0xab, 0x7a, 0x84, 0xfe, 0x8e, 0x5d, 0x7b, 0x50,
	0xcb, 0x97, 0x55, 0xc5, 0xf2, 0x76, 0x68, 0xc6, 0x6e, 0xba, 0xda, 0xe1, 0x4d, 0x15, 0xbb, 0xaf,
	0xa8, 0x35, 0x52, 0xe1, 0xe7, 0x43, 0x3b, 0x76, 0x53, 0x0d, 0xaf, 0x2f, 0x9f, 0xcf, 0xdf, 0x8e,
	0xec, 0x3a, 0x0b, 0x8d, 0x41, 0x9a, 0x59, 0x5b, 0xe5, 0xa2, 0xf6, 0xb8, 0x1a, 0xf9, 0x7f, 0xa7,
	0x3c, 0xf1, 0xd3, 0x7c, 0x79, 0xe0, 0xd3, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x21, 0x16,
	0xfa, 0xf1, 0x00, 0x00, 0x00,
}
