// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/types/events.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type EventDataRoundState struct {
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round                int32    `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Step                 string   `protobuf:"bytes,3,opt,name=step,proto3" json:"step,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventDataRoundState) Reset()         { *m = EventDataRoundState{} }
func (m *EventDataRoundState) String() string { return proto.CompactTextString(m) }
func (*EventDataRoundState) ProtoMessage()    {}
func (*EventDataRoundState) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bb9bdae76a076d6, []int{0}
}
func (m *EventDataRoundState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventDataRoundState.Unmarshal(m, b)
}
func (m *EventDataRoundState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventDataRoundState.Marshal(b, m, deterministic)
}
func (m *EventDataRoundState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDataRoundState.Merge(m, src)
}
func (m *EventDataRoundState) XXX_Size() int {
	return xxx_messageInfo_EventDataRoundState.Size(m)
}
func (m *EventDataRoundState) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDataRoundState.DiscardUnknown(m)
}

var xxx_messageInfo_EventDataRoundState proto.InternalMessageInfo

func (m *EventDataRoundState) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *EventDataRoundState) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *EventDataRoundState) GetStep() string {
	if m != nil {
		return m.Step
	}
	return ""
}

func init() {
	proto.RegisterType((*EventDataRoundState)(nil), "tendermint.proto.types.EventDataRoundState")
}

func init() { proto.RegisterFile("proto/types/events.proto", fileDescriptor_1bb9bdae76a076d6) }

var fileDescriptor_1bb9bdae76a076d6 = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0xb1, 0xaa, 0xc2, 0x30,
	0x18, 0x46, 0xc9, 0xed, 0x6d, 0xc1, 0x8c, 0x51, 0x4a, 0xc6, 0xe2, 0xd4, 0x29, 0x11, 0x7c, 0x03,
	0xd1, 0x17, 0x88, 0x83, 0xe0, 0x96, 0x36, 0x3f, 0x4d, 0xc0, 0x26, 0xa5, 0xf9, 0x23, 0xf8, 0xf6,
	0xd2, 0x54, 0xd0, 0xed, 0x3b, 0x1f, 0x67, 0x38, 0x94, 0x4f, 0x73, 0xc0, 0x20, 0xf1, 0x35, 0x41,
	0x94, 0xf0, 0x04, 0x8f, 0x51, 0xe4, 0x8b, 0xd5, 0x08, 0xde, 0xc0, 0x3c, 0x3a, 0x8f, 0xeb, 0x23,
	0xb2, 0xb4, 0xbf, 0xd1, 0xed, 0x65, 0xf1, 0xce, 0x1a, 0xb5, 0x0a, 0xc9, 0x9b, 0x2b, 0x6a, 0x04,
	0x56, 0xd3, 0xca, 0x82, 0x1b, 0x2c, 0x72, 0xd2, 0x90, 0xb6, 0x50, 0x1f, 0x62, 0x3b, 0x5a, 0xce,
	0x8b, 0xc5, 0xff, 0x1a, 0xd2, 0x96, 0x6a, 0x05, 0xc6, 0xe8, 0x7f, 0x44, 0x98, 0x78, 0xd1, 0x90,
	0x76, 0xa3, 0xf2, 0x3e, 0x1d, 0xee, 0x62, 0x70, 0x68, 0x53, 0x27, 0xfa, 0x30, 0x4a, 0xd3, 0xf5,
	0x56, 0x3b, 0xdf, 0x3f, 0x42, 0x32, 0xf2, 0x9b, 0x22, 0x7f, 0x7a, 0xbb, 0x2a, 0xc3, 0xf1, 0x1d,
	0x00, 0x00, 0xff, 0xff, 0xd5, 0x4c, 0x40, 0x66, 0xc5, 0x00, 0x00, 0x00,
}
