// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/types/validator.proto

package types

import (
	fmt "fmt"
	keys "github.com/dbchaincloud/tendermint/proto/crypto/keys"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ValidatorSet struct {
	Validators           []*Validator `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators,omitempty"`
	Proposer             *Validator   `protobuf:"bytes,2,opt,name=proposer,proto3" json:"proposer,omitempty"`
	TotalVotingPower     int64        `protobuf:"varint,3,opt,name=total_voting_power,json=totalVotingPower,proto3" json:"total_voting_power,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ValidatorSet) Reset()         { *m = ValidatorSet{} }
func (m *ValidatorSet) String() string { return proto.CompactTextString(m) }
func (*ValidatorSet) ProtoMessage()    {}
func (*ValidatorSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e7c6b38c20e5406, []int{0}
}
func (m *ValidatorSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorSet.Unmarshal(m, b)
}
func (m *ValidatorSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorSet.Marshal(b, m, deterministic)
}
func (m *ValidatorSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorSet.Merge(m, src)
}
func (m *ValidatorSet) XXX_Size() int {
	return xxx_messageInfo_ValidatorSet.Size(m)
}
func (m *ValidatorSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorSet.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorSet proto.InternalMessageInfo

func (m *ValidatorSet) GetValidators() []*Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

func (m *ValidatorSet) GetProposer() *Validator {
	if m != nil {
		return m.Proposer
	}
	return nil
}

func (m *ValidatorSet) GetTotalVotingPower() int64 {
	if m != nil {
		return m.TotalVotingPower
	}
	return 0
}

type Validator struct {
	Address              []byte         `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PubKey               keys.PublicKey `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key"`
	VotingPower          int64          `protobuf:"varint,3,opt,name=voting_power,json=votingPower,proto3" json:"voting_power,omitempty"`
	ProposerPriority     int64          `protobuf:"varint,4,opt,name=proposer_priority,json=proposerPriority,proto3" json:"proposer_priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Validator) Reset()         { *m = Validator{} }
func (m *Validator) String() string { return proto.CompactTextString(m) }
func (*Validator) ProtoMessage()    {}
func (*Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e7c6b38c20e5406, []int{1}
}
func (m *Validator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Validator.Unmarshal(m, b)
}
func (m *Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Validator.Marshal(b, m, deterministic)
}
func (m *Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validator.Merge(m, src)
}
func (m *Validator) XXX_Size() int {
	return xxx_messageInfo_Validator.Size(m)
}
func (m *Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_Validator proto.InternalMessageInfo

func (m *Validator) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Validator) GetPubKey() keys.PublicKey {
	if m != nil {
		return m.PubKey
	}
	return keys.PublicKey{}
}

func (m *Validator) GetVotingPower() int64 {
	if m != nil {
		return m.VotingPower
	}
	return 0
}

func (m *Validator) GetProposerPriority() int64 {
	if m != nil {
		return m.ProposerPriority
	}
	return 0
}

func init() {
	proto.RegisterType((*ValidatorSet)(nil), "tendermint.proto.types.ValidatorSet")
	proto.RegisterType((*Validator)(nil), "tendermint.proto.types.Validator")
}

func init() { proto.RegisterFile("proto/types/validator.proto", fileDescriptor_2e7c6b38c20e5406) }

var fileDescriptor_2e7c6b38c20e5406 = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x31, 0x4f, 0xeb, 0x30,
	0x10, 0xc7, 0x5f, 0x5e, 0xab, 0xf6, 0x3d, 0xb7, 0x03, 0x78, 0x40, 0x51, 0x11, 0xa2, 0xed, 0x00,
	0x95, 0x40, 0x36, 0x82, 0x99, 0x81, 0x0e, 0x2c, 0x5d, 0xaa, 0x20, 0x75, 0x60, 0x89, 0x92, 0xd8,
	0x4a, 0xad, 0xa6, 0x39, 0xcb, 0xb9, 0x14, 0xf9, 0xc3, 0xc1, 0xcc, 0xa7, 0xe0, 0xb3, 0xa0, 0xc6,
	0x4d, 0x5a, 0x89, 0x0e, 0x6c, 0xb9, 0xff, 0xff, 0xee, 0x7f, 0xbf, 0x9c, 0x4c, 0xce, 0xb5, 0x01,
	0x04, 0x8e, 0x56, 0xcb, 0x82, 0x6f, 0xa2, 0x4c, 0x89, 0x08, 0xc1, 0xb0, 0x4a, 0xa5, 0x67, 0x28,
	0x73, 0x21, 0xcd, 0x5a, 0xe5, 0xe8, 0x14, 0x56, 0xf5, 0x0d, 0xae, 0x70, 0xa9, 0x8c, 0x08, 0x75,
	0x64, 0xd0, 0x72, 0x17, 0x90, 0x42, 0x0a, 0xfb, 0x2f, 0xd7, 0x3d, 0xb8, 0x70, 0x4a, 0x62, 0xac,
	0x46, 0xe0, 0x2b, 0x69, 0x0b, 0xb7, 0xc8, 0xd9, 0xe3, 0x0f, 0x8f, 0xf4, 0x17, 0xf5, 0xca, 0x17,
	0x89, 0xf4, 0x89, 0x90, 0x06, 0xa1, 0xf0, 0xbd, 0x61, 0x6b, 0xd2, 0xbb, 0x1f, 0xb1, 0xe3, 0x10,
	0xac, 0x99, 0x0c, 0x0e, 0x86, 0xe8, 0x23, 0xf9, 0xa7, 0x0d, 0x68, 0x28, 0xa4, 0xf1, 0xff, 0x0e,
	0xbd, 0xdf, 0x05, 0x34, 0x23, 0xf4, 0x96, 0x50, 0x04, 0x8c, 0xb2, 0x70, 0x03, 0xa8, 0xf2, 0x34,
	0xd4, 0xf0, 0x26, 0x8d, 0xdf, 0x1a, 0x7a, 0x93, 0x56, 0x70, 0x52, 0x39, 0x8b, 0xca, 0x98, 0x6f,
	0xf5, 0xf1, 0xbb, 0x47, 0xfe, 0x37, 0x29, 0xd4, 0x27, 0xdd, 0x48, 0x08, 0x23, 0x8b, 0x2d, 0xba,
	0x37, 0xe9, 0x07, 0x75, 0x49, 0x9f, 0x49, 0x57, 0x97, 0x71, 0xb8, 0x92, 0x76, 0xc7, 0x74, 0xfd,
	0x93, 0xc9, 0x1d, 0x89, 0x6d, 0x8f, 0xc4, 0xe6, 0x65, 0x9c, 0xa9, 0x64, 0x26, 0xed, 0xb4, 0xfd,
	0xf9, 0x75, 0xf9, 0x27, 0xe8, 0xe8, 0x32, 0x9e, 0x49, 0x4b, 0x47, 0xa4, 0x7f, 0x84, 0xab, 0xb7,
	0xd9, 0x23, 0xd1, 0x1b, 0x72, 0x5a, 0xff, 0x4c, 0xa8, 0x8d, 0x02, 0xa3, 0xd0, 0xfa, 0x6d, 0xc7,
	0x5f, 0x1b, 0xf3, 0x9d, 0x3e, 0xbd, 0x7b, 0x65, 0xa9, 0xc2, 0x65, 0x19, 0xb3, 0x04, 0xd6, 0x5c,
	0xc4, 0xc9, 0x32, 0x52, 0x79, 0x92, 0x41, 0x29, 0xf8, 0x9e, 0x8f, 0x1f, 0xbc, 0x90, 0xb8, 0x53,
	0x15, 0x0f, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xdc, 0xea, 0x10, 0x64, 0x37, 0x02, 0x00, 0x00,
}
