// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/privval/types.proto

package privval

import (
	fmt "fmt"
	keys "github.com/dbchaincloud/tendermint/proto/crypto/keys"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// FilePVKey stores the immutable part of PrivValidator.
type FilePVKey struct {
	Address              []byte          `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PubKey               keys.PublicKey  `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key"`
	PrivKey              keys.PrivateKey `protobuf:"bytes,3,opt,name=priv_key,json=privKey,proto3" json:"priv_key"`
	FilePath             string          `protobuf:"bytes,4,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FilePVKey) Reset()         { *m = FilePVKey{} }
func (m *FilePVKey) String() string { return proto.CompactTextString(m) }
func (*FilePVKey) ProtoMessage()    {}
func (*FilePVKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d74c406df3ad93, []int{0}
}
func (m *FilePVKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilePVKey.Unmarshal(m, b)
}
func (m *FilePVKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilePVKey.Marshal(b, m, deterministic)
}
func (m *FilePVKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilePVKey.Merge(m, src)
}
func (m *FilePVKey) XXX_Size() int {
	return xxx_messageInfo_FilePVKey.Size(m)
}
func (m *FilePVKey) XXX_DiscardUnknown() {
	xxx_messageInfo_FilePVKey.DiscardUnknown(m)
}

var xxx_messageInfo_FilePVKey proto.InternalMessageInfo

func (m *FilePVKey) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *FilePVKey) GetPubKey() keys.PublicKey {
	if m != nil {
		return m.PubKey
	}
	return keys.PublicKey{}
}

func (m *FilePVKey) GetPrivKey() keys.PrivateKey {
	if m != nil {
		return m.PrivKey
	}
	return keys.PrivateKey{}
}

func (m *FilePVKey) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

// FilePVLastSignState stores the mutable part of PrivValidator.
type FilePVLastSignState struct {
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round                int64    `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Step                 int32    `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`
	Signature            []byte   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	SignBytes            []byte   `protobuf:"bytes,5,opt,name=sign_bytes,json=signBytes,proto3" json:"sign_bytes,omitempty"`
	FilePath             string   `protobuf:"bytes,6,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilePVLastSignState) Reset()         { *m = FilePVLastSignState{} }
func (m *FilePVLastSignState) String() string { return proto.CompactTextString(m) }
func (*FilePVLastSignState) ProtoMessage()    {}
func (*FilePVLastSignState) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d74c406df3ad93, []int{1}
}
func (m *FilePVLastSignState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilePVLastSignState.Unmarshal(m, b)
}
func (m *FilePVLastSignState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilePVLastSignState.Marshal(b, m, deterministic)
}
func (m *FilePVLastSignState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilePVLastSignState.Merge(m, src)
}
func (m *FilePVLastSignState) XXX_Size() int {
	return xxx_messageInfo_FilePVLastSignState.Size(m)
}
func (m *FilePVLastSignState) XXX_DiscardUnknown() {
	xxx_messageInfo_FilePVLastSignState.DiscardUnknown(m)
}

var xxx_messageInfo_FilePVLastSignState proto.InternalMessageInfo

func (m *FilePVLastSignState) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *FilePVLastSignState) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *FilePVLastSignState) GetStep() int32 {
	if m != nil {
		return m.Step
	}
	return 0
}

func (m *FilePVLastSignState) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *FilePVLastSignState) GetSignBytes() []byte {
	if m != nil {
		return m.SignBytes
	}
	return nil
}

func (m *FilePVLastSignState) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func init() {
	proto.RegisterType((*FilePVKey)(nil), "tendermint.proto.privval.FilePVKey")
	proto.RegisterType((*FilePVLastSignState)(nil), "tendermint.proto.privval.FilePVLastSignState")
}

func init() { proto.RegisterFile("proto/privval/types.proto", fileDescriptor_a9d74c406df3ad93) }

var fileDescriptor_a9d74c406df3ad93 = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x8e, 0xda, 0x30,
	0x14, 0x6e, 0x0a, 0x04, 0xe2, 0xb2, 0x72, 0xab, 0x2a, 0xa5, 0x45, 0x45, 0x2c, 0xda, 0xac, 0x92,
	0x8a, 0xde, 0x80, 0x05, 0x52, 0x45, 0x17, 0x28, 0x48, 0x5d, 0x74, 0x13, 0x39, 0xc9, 0x6b, 0x62,
	0x11, 0x62, 0xcb, 0x7e, 0x41, 0xf2, 0xb1, 0x7a, 0x8b, 0xb9, 0xc0, 0x6c, 0xe7, 0x2c, 0x23, 0x3b,
	0x8c, 0x32, 0x68, 0x16, 0xb3, 0x7b, 0xdf, 0xe7, 0xe7, 0xef, 0xc7, 0x32, 0xf9, 0x24, 0x95, 0x40,
	0x91, 0x48, 0xc5, 0x2f, 0x17, 0xd6, 0x24, 0x68, 0x24, 0xe8, 0xd8, 0x71, 0x34, 0x44, 0x68, 0x4b,
	0x50, 0x67, 0xde, 0x62, 0xcf, 0xc4, 0xd7, 0xad, 0xc5, 0x37, 0xac, 0xb9, 0x2a, 0x33, 0xc9, 0x14,
	0x9a, 0xa4, 0x17, 0xa8, 0x44, 0x25, 0x86, 0xa9, 0xdf, 0x5f, 0x2c, 0x7b, 0xa6, 0x50, 0x46, 0xa2,
	0x48, 0x4e, 0x60, 0xf4, 0x73, 0x83, 0xf5, 0xbd, 0x47, 0x82, 0x1d, 0x6f, 0xe0, 0xf0, 0x67, 0x0f,
	0x86, 0x86, 0x64, 0xca, 0xca, 0x52, 0x81, 0xd6, 0xa1, 0xb7, 0xf2, 0xa2, 0x79, 0xfa, 0x04, 0xe9,
	0x8e, 0x4c, 0x65, 0x97, 0x67, 0x27, 0x30, 0xe1, 0xdb, 0x95, 0x17, 0xbd, 0xdb, 0x7c, 0x8f, 0x5f,
	0x44, 0xeb, 0x3d, 0x62, 0xeb, 0x11, 0x1f, 0xba, 0xbc, 0xe1, 0xc5, 0x1e, 0xcc, 0x76, 0x7c, 0xf7,
	0xf0, 0xf5, 0x4d, 0xea, 0xcb, 0x2e, 0xb7, 0x0e, 0xbf, 0xc8, 0xcc, 0x36, 0x70, 0x42, 0x23, 0x27,
	0x14, 0xbd, 0x22, 0xa4, 0xf8, 0x85, 0x21, 0x0c, 0x4a, 0x53, 0x7b, 0xdf, 0x4a, 0x7d, 0x26, 0xc1,
	0x3f, 0xde, 0x40, 0x26, 0x19, 0xd6, 0xe1, 0x78, 0xe5, 0x45, 0x41, 0x3a, 0xb3, 0xc4, 0x81, 0x61,
	0xbd, 0xfe, 0xef, 0x91, 0xf7, 0x7d, 0xaf, 0xdf, 0x4c, 0xe3, 0x91, 0x57, 0xed, 0x11, 0x19, 0x02,
	0xfd, 0x48, 0xfc, 0x1a, 0x78, 0x55, 0xa3, 0x2b, 0x38, 0x4a, 0xaf, 0x88, 0x7e, 0x20, 0x13, 0x25,
	0xba, 0xb6, 0x74, 0xed, 0x46, 0x69, 0x0f, 0x28, 0x25, 0x63, 0x8d, 0x20, 0x5d, 0xd2, 0x49, 0xea,
	0x66, 0xfa, 0x85, 0x04, 0x9a, 0x57, 0x2d, 0xc3, 0x4e, 0x81, 0xb3, 0x9d, 0xa7, 0x03, 0x41, 0x97,
	0x84, 0x58, 0x90, 0xe5, 0x06, 0x41, 0x87, 0x93, 0xe1, 0x78, 0x6b, 0x89, 0xdb, 0xcc, 0xfe, 0x6d,
	0xe6, 0xed, 0xe6, 0xef, 0x8f, 0x8a, 0x63, 0xdd, 0xe5, 0x71, 0x21, 0xce, 0x49, 0x99, 0x17, 0x35,
	0xe3, 0x6d, 0xd1, 0x88, 0xae, 0x4c, 0x86, 0x27, 0x4a, 0x6e, 0x3e, 0x4b, 0xee, 0x3b, 0xf8, 0xf3,
	0x31, 0x00, 0x00, 0xff, 0xff, 0x04, 0x95, 0xc1, 0x5f, 0x44, 0x02, 0x00, 0x00,
}
